### ISSUE TITLE
Pickling Error MultithreadSLIM

### ISSUE THREAD

**Issue by umbertoDifa** [mquad/recsys-course-2016-pub#2]
Ciao, il multithreadSLIM mi da un errore quando viene chiamata la .fit :
`PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed`

Il codice che sto tentando di eseguire e' : 
```
recommender = MultiThreadSLIM(l1_penalty=0.1,l2_penalty=0.01)

train_size = int(data.shape[0] * 0.8)
# split data according to the shuffled index and the holdout size
train_split = data[:train_size]
test_split = data[train_size:]

recommender.fit(train_split)
```
Dove data e' una matrice in formato csc.

Qualcuno sa la causa di questo errore?

Grazie :)

**Comment by mquad** [comment]
Hi @umbertoDifa , what version of python are you currently using? Have you made any changes to the `MultiThreadSLIM ` class?

**Comment by umbertoDifa** [comment]
Hi @mquad , I'm using python 2.7, no I have not made any changes.
By the way, I attach the code and the dataset to replicate the error.

[mySLIM.zip](https://github.com/mquad/recsys-course-2016-pub/files/606394/mySLIM.zip)

**Comment by mquad** [comment]
As written in the Install instructions in the README.md, only python3.5 or above are supported. Please setup python3.5 and try again.

**Comment by umbertoDifa** [comment]
Thanks, that was the problem.

**Comment by mquad** [comment]
You are welcome 😄  I updated the Readme.md to make this point clear for everybody.
